### ISSUE TITLE
What are the names and versions of the libraries, etc. that you need?

### ISSUE THREAD

**Issue by atusi-nakajima** [SysCV/spc2#4]
What are the names and versions of the libraries, etc. that you need?
It would also be helpful if you could tell us the version of your runtime environment if possible.
I'm trying to run it on carla0.9.6 or 0.9.8.

**Comment by noahcao** [comment]
When I ran it on CARLA, I use **0.8.4** as the default CARLA8 environment (also the main experiment environment) and **0.9.5** for CARLA9.

You don't need any additional environment settings except for what is needed to run 0.9.6. Because this repo is basically the client side implementation in python and the environment dependency for different carla versions should be handled when you build the simulator side.

Note: 
1. One main reason I used 0.9.5 was that pip only supports version no later than 0.9.5 then. If you'd like to run it on later version, you have to compile the python library yourself.
2. You should set the "--env" flag to be "carla9" to run on CARLA9. 
3. You could check the implementation for CARLA9 support in [carla9.py](https://github.com/SysCV/spc2/blob/master/envs/CARLA/carla9.py) for implementation details. 
4. If I were right, [carla9.py](https://github.com/SysCV/spc2/blob/master/envs/CARLA/carla9.py) supports 0.9.6 and 0.9.5 already. But if you need to use 0.9.8, you may have to make some changes because from 0.9.6 to 0.9.8, some APIs are changed.

**Comment by atusi-nakajima** [comment]
Thanks for the reply.
I changed the version to carla0.9.5.
I'll ask again because there's something I don't understand.

Currently I have built carla0.9.5 from source [(reference)](https://carla.readthedocs.io/en/0.9.5/how_to_build_on_linux/) and put pretrained weights in spc2/pretrain/ folder.
Then I changed --env carla8 to carla9 in the following files in scripts (auto_client.sh debug_carla.sh test_carla.sh train_carla.sh).
Then start carla `SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=0 . /CarlaUE4.sh -carla-settings=Example.CarlaSettings.ini -windowed -ResX=256 -ResY=256 -carla-server -carla-no-hud`
I tried to run` bash train_carla.sh` from a different terminal, but it wouldn't run with errors like "ImportError: No module named numpy".　
I'm sure it's already installed with pip, and it's listed in the pip list.
Please let me know if there is anything I can do.
Thanks in advance.

**Comment by noahcao** [comment]
Hi Atusi,

I tried the same pipeline as you did, I believe you can simply fix that by just installing numpy in the docker container. Some potential issues causing the problem:

1. tricky library sourcing problem, which sometimes happens when you use pip and conda at the same time, you could fix this by simply reinstalling it by conda/pip as the new conda version woks well with built-in pip environment.
2. Reinstall the whole pytorch pipeline to avoid some potential numpy-torch dependency problem, which I heard might cause the false "ImportError" problem.

I'm closing this issue because it's not directly related to the main content of this repo but please feel free to put any follow-ups.
